services:
  # --- BANCO DEV (Persistente no Disco) ---
  postgres:
    image: postgres:latest
    container_name: fastify_pg_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ecommerce_dev
      # CORREÇÃO CRÍTICA 1: Força os dados para uma subpasta
      PGDATA: /var/lib/postgresql/data/pgdata 
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  # --- BANCO TESTES (Volátil na RAM - Super Rápido) ---
  postgres_test:
    image: postgres:latest
    container_name: fastify_pg_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ecommerce_test
      # CORREÇÃO CRÍTICA 2: Mesma coisa aqui, senão o tmpfs falha
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    tmpfs: 
      - /var/lib/postgresql/data

  # --- API BACKEND (Hot Reload) ---
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
      target: builder
    container_name: fastify_api_dev
    command: npm run dev
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      # Ajuste: Apenas para garantir, vamos remover o ?schema=public da string por enquanto
      # para evitar erros de parser, o padrão já é public.
      - DATABASE_URL=postgresql://postgres:docker@postgres:5432/ecommerce_dev
      - JWT_SECRET=dev-secret-key
      - NODE_ENV=development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata_dev: