services:
  # -------------------------
  # BANCO DE DADOS (Postgres)
  # -------------------------
  db:
    image: postgres:18-alpine
    container_name: croche-db
    restart: unless-stopped
    env_file:
      - ./server/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - croche-net

  # -------------------------
  # API / SERVER
  # -------------------------
  api:
    image: josivaljunior/croche-api:latest
    container_name: croche-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./server/.env.prod
    ports:
      - "3333:3333"
    networks:
      - croche-net

  # -------------------------
  # WEB / FRONTEND
  # -------------------------
  web:
    image: josivaljunior/croche-web:latest
    container_name: croche-web
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      - ./web/.env.prod
    ports:
      - "3000:3000"
    networks:
      - croche-net

volumes:
  postgres_data:

networks:
  croche-net:
