name: CD (Build & Publish)

on:
  push:
    branches: [main] # Produção

jobs:
  deploy-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Habilita emulador QEMU (caso precise buildar para ARM/Apple Silicon no futuro)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Configura o Buildx (engine de build avançada do Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/croche-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/croche-api:${{ github.sha }}
          # --- OTIMIZAÇÃO PROFISSIONAL ---
          # Usa o cache interno do GitHub Actions para guardar as camadas do Docker
          cache-from: type=gha
          cache-to: type=gha,mode=max