name: CD (Build & Publish)

on:
  push:
    branches: [main]

jobs:
  # ---------------------------------------------------
  # JOB 1: BUILD & PUSH DA API (BACKEND)
  # ---------------------------------------------------
  build-push-api:
    name: API - Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/croche-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/croche-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ---------------------------------------------------
  # JOB 2: BUILD & PUSH DA WEB (FRONTEND)
  # ---------------------------------------------------
  build-push-web:
    name: Web - Build & Push
    runs-on: ubuntu-latest
    needs: [build-push-api] # garante ordem l√≥gica (API primeiro)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Web
        uses: docker/build-push-action@v5
        with:
          context: .
          file: web/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/croche-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/croche-web:${{ github.sha }}

          # Alinhado com o Dockerfile do web (code 3)
          build-args: |
            NEXT_PUBLIC_API_URL=http://localhost:3333
            API_INTERNAL_URL=http://localhost:3333

          cache-from: type=gha
          cache-to: type=gha,mode=max
